version: '3.8'

services:
  api:
    image: merchstore/backend
    build: .
    command: >
      sh -c "
      python /app/manage.py collectstatic --noinput &&
      python /app/manage.py makemigrations &&
      python /app/manage.py migrate &&
      gunicorn --chdir /app backend.wsgi:application --bind 0.0.0.0:3376
      "
    volumes:
      - .:/app
      - ./logs/:/app/logs/
      - ./media/:/app/media/
      - ./static/:/app/static/
    ports:
      - "3377:3376"
